var annotated =
[
    [ "axis_to_type< N >", "structaxis__to__type.html", "structaxis__to__type" ],
    [ "xpath_parser::binary_op_t", "structxpath__parser_1_1binary__op__t.html", "structxpath__parser_1_1binary__op__t" ],
    [ "buffer_holder", "structbuffer__holder.html", "structbuffer__holder" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "DataHandler", "class_data_handler.html", "class_data_handler" ],
    [ "document_order_comparator", "structdocument__order__comparator.html", "structdocument__order__comparator" ],
    [ "duplicate_comparator", "structduplicate__comparator.html", "structduplicate__comparator" ],
    [ "equal_to", "structequal__to.html", "structequal__to" ],
    [ "FBOstruct", "struct_f_b_ostruct.html", "struct_f_b_ostruct" ],
    [ "FlowSource", "class_flow_source.html", "class_flow_source" ],
    [ "gap", "structgap.html", "structgap" ],
    [ "latin1_writer", "structlatin1__writer.html", "structlatin1__writer" ],
    [ "less", "structless.html", "structless" ],
    [ "less_equal", "structless__equal.html", "structless__equal" ],
    [ "mapdata", "structmapdata.html", "structmapdata" ],
    [ "Mesh", "struct_mesh.html", "struct_mesh" ],
    [ "Model", "struct_model.html", "struct_model" ],
    [ "namespace_uri_predicate", "structnamespace__uri__predicate.html", "structnamespace__uri__predicate" ],
    [ "not_equal_to", "structnot__equal__to.html", "structnot__equal__to" ],
    [ "opt_false", "structopt__false.html", null ],
    [ "opt_true", "structopt__true.html", null ],
    [ "strconv_attribute_impl< opt_escape >", "structstrconv__attribute__impl.html", "structstrconv__attribute__impl" ],
    [ "strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >", "structstrconv__pcdata__impl.html", "structstrconv__pcdata__impl" ],
    [ "TextureData", "struct_texture_data.html", "struct_texture_data" ],
    [ "utf16_counter", "structutf16__counter.html", "structutf16__counter" ],
    [ "utf16_writer", "structutf16__writer.html", "structutf16__writer" ],
    [ "utf32_counter", "structutf32__counter.html", "structutf32__counter" ],
    [ "utf32_writer", "structutf32__writer.html", "structutf32__writer" ],
    [ "utf8_counter", "structutf8__counter.html", "structutf8__counter" ],
    [ "utf8_writer", "structutf8__writer.html", "structutf8__writer" ],
    [ "utf_decoder< Traits, opt_swap >", "structutf__decoder.html", "structutf__decoder" ],
    [ "wchar_selector< 2 >", "structwchar__selector_3_012_01_4.html", "structwchar__selector_3_012_01_4" ],
    [ "wchar_selector< 4 >", "structwchar__selector_3_014_01_4.html", "structwchar__selector_3_014_01_4" ],
    [ "xml_allocator", "structxml__allocator.html", "structxml__allocator" ],
    [ "pugi::xml_attribute_struct", "structpugi_1_1xml__attribute__struct.html", "structpugi_1_1xml__attribute__struct" ],
    [ "xml_buffered_writer", "classxml__buffered__writer.html", "classxml__buffered__writer" ],
    [ "xml_document_struct", "structxml__document__struct.html", "structxml__document__struct" ],
    [ "xml_extra_buffer", "structxml__extra__buffer.html", "structxml__extra__buffer" ],
    [ "xml_memory_management_function_storage< T >", "structxml__memory__management__function__storage.html", "structxml__memory__management__function__storage" ],
    [ "xml_memory_page", "structxml__memory__page.html", "structxml__memory__page" ],
    [ "xml_memory_string_header", "structxml__memory__string__header.html", "structxml__memory__string__header" ],
    [ "pugi::xml_node_struct", "structpugi_1_1xml__node__struct.html", "structpugi_1_1xml__node__struct" ],
    [ "xml_parser", "structxml__parser.html", "structxml__parser" ],
    [ "xml_stream_chunk< T >", "structxml__stream__chunk.html", "structxml__stream__chunk" ],
    [ "xpath_allocator", "classxpath__allocator.html", "classxpath__allocator" ],
    [ "xpath_allocator_capture", "structxpath__allocator__capture.html", "structxpath__allocator__capture" ],
    [ "xpath_ast_node", "classxpath__ast__node.html", "classxpath__ast__node" ],
    [ "xpath_context", "structxpath__context.html", "structxpath__context" ],
    [ "xpath_lexer", "classxpath__lexer.html", "classxpath__lexer" ],
    [ "xpath_lexer_string", "structxpath__lexer__string.html", "structxpath__lexer__string" ],
    [ "xpath_memory_block", "structxpath__memory__block.html", "structxpath__memory__block" ],
    [ "xpath_node_set_raw", "classxpath__node__set__raw.html", "classxpath__node__set__raw" ],
    [ "xpath_parser", "structxpath__parser.html", "structxpath__parser" ],
    [ "xpath_query_impl", "structxpath__query__impl.html", "structxpath__query__impl" ],
    [ "xpath_stack", "structxpath__stack.html", "structxpath__stack" ],
    [ "xpath_stack_data", "structxpath__stack__data.html", "structxpath__stack__data" ],
    [ "xpath_string", "classxpath__string.html", "classxpath__string" ],
    [ "xpath_variable_boolean", "structxpath__variable__boolean.html", "structxpath__variable__boolean" ],
    [ "xpath_variable_node_set", "structxpath__variable__node__set.html", "structxpath__variable__node__set" ],
    [ "xpath_variable_number", "structxpath__variable__number.html", "structxpath__variable__number" ],
    [ "xpath_variable_string", "structxpath__variable__string.html", "structxpath__variable__string" ]
];