var hierarchy =
[
    [ "axis_to_type< N >", "structaxis__to__type.html", null ],
    [ "xpath_parser::binary_op_t", "structxpath__parser_1_1binary__op__t.html", null ],
    [ "buffer_holder", "structbuffer__holder.html", null ],
    [ "Camera", "class_camera.html", null ],
    [ "DataHandler", "class_data_handler.html", null ],
    [ "document_order_comparator", "structdocument__order__comparator.html", null ],
    [ "duplicate_comparator", "structduplicate__comparator.html", null ],
    [ "equal_to", "structequal__to.html", null ],
    [ "FBOstruct", "struct_f_b_ostruct.html", null ],
    [ "FlowSource", "class_flow_source.html", null ],
    [ "gap", "structgap.html", null ],
    [ "latin1_writer", "structlatin1__writer.html", null ],
    [ "less", "structless.html", null ],
    [ "less_equal", "structless__equal.html", null ],
    [ "mapdata", "structmapdata.html", null ],
    [ "Mesh", "struct_mesh.html", null ],
    [ "Model", "struct_model.html", null ],
    [ "namespace_uri_predicate", "structnamespace__uri__predicate.html", null ],
    [ "not_equal_to", "structnot__equal__to.html", null ],
    [ "opt_false", "structopt__false.html", null ],
    [ "opt_true", "structopt__true.html", null ],
    [ "strconv_attribute_impl< opt_escape >", "structstrconv__attribute__impl.html", null ],
    [ "strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >", "structstrconv__pcdata__impl.html", null ],
    [ "TextureData", "struct_texture_data.html", null ],
    [ "utf16_counter", "structutf16__counter.html", null ],
    [ "utf16_writer", "structutf16__writer.html", null ],
    [ "utf32_counter", "structutf32__counter.html", null ],
    [ "utf32_writer", "structutf32__writer.html", null ],
    [ "utf8_counter", "structutf8__counter.html", null ],
    [ "utf8_writer", "structutf8__writer.html", null ],
    [ "utf_decoder< Traits, opt_swap >", "structutf__decoder.html", null ],
    [ "wchar_selector< 2 >", "structwchar__selector_3_012_01_4.html", null ],
    [ "wchar_selector< 4 >", "structwchar__selector_3_014_01_4.html", null ],
    [ "xml_allocator", "structxml__allocator.html", [
      [ "xml_document_struct", "structxml__document__struct.html", null ]
    ] ],
    [ "pugi::xml_attribute_struct", "structpugi_1_1xml__attribute__struct.html", null ],
    [ "xml_buffered_writer", "classxml__buffered__writer.html", null ],
    [ "xml_extra_buffer", "structxml__extra__buffer.html", null ],
    [ "xml_memory_management_function_storage< T >", "structxml__memory__management__function__storage.html", null ],
    [ "xml_memory_page", "structxml__memory__page.html", null ],
    [ "xml_memory_string_header", "structxml__memory__string__header.html", null ],
    [ "pugi::xml_node_struct", "structpugi_1_1xml__node__struct.html", null ],
    [ "xml_parser", "structxml__parser.html", null ],
    [ "xml_stream_chunk< T >", "structxml__stream__chunk.html", null ],
    [ "xpath_allocator", "classxpath__allocator.html", null ],
    [ "xpath_allocator_capture", "structxpath__allocator__capture.html", null ],
    [ "xpath_ast_node", "classxpath__ast__node.html", null ],
    [ "xpath_context", "structxpath__context.html", null ],
    [ "xpath_lexer", "classxpath__lexer.html", null ],
    [ "xpath_lexer_string", "structxpath__lexer__string.html", null ],
    [ "xpath_memory_block", "structxpath__memory__block.html", null ],
    [ "xpath_node_set_raw", "classxpath__node__set__raw.html", null ],
    [ "xpath_parser", "structxpath__parser.html", null ],
    [ "xpath_query_impl", "structxpath__query__impl.html", null ],
    [ "xpath_stack", "structxpath__stack.html", null ],
    [ "xpath_stack_data", "structxpath__stack__data.html", null ],
    [ "xpath_string", "classxpath__string.html", null ],
    [ "xpath_variable_boolean", "structxpath__variable__boolean.html", null ],
    [ "xpath_variable_node_set", "structxpath__variable__node__set.html", null ],
    [ "xpath_variable_number", "structxpath__variable__number.html", null ],
    [ "xpath_variable_string", "structxpath__variable__string.html", null ]
];